# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mudur', '0001_new_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=200, unique=True, verbose_name='Fonksiyon ismi')),
                ('subject', models.CharField(max_length=300, verbose_name='Konu')),
                ('body_html', models.TextField(max_length=2000, verbose_name='HTML E-posta Govdesi')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudur.Site')),
            ],
            options={
                'verbose_name': 'E-posta sablonu',
                'verbose_name_plural': 'E-posta sablonlari',
            },
        ),
    ]
