# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(max_length=2000, verbose_name='HTML E-posta Govdesi'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='operation_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Fonksiyon ismi'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='Konu'),
        ),
    ]
