# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 22:56
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500, verbose_name='Detail')),
                ('is_right', models.BooleanField(default=False, verbose_name='Is Right Answer')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='ApprovalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='End Date')),
                ('preference_order', models.SmallIntegerField(verbose_name='Preference')),
                ('for_instructor', models.BooleanField(default=True, verbose_name='For Instructor?')),
                ('for_trainess', models.BooleanField(default=False, verbose_name='For Trainess?')),
            ],
            options={
                'verbose_name': 'Approval Date',
                'verbose_name_plural': 'Approval Dates',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Content Name')),
                ('content', ckeditor.fields.RichTextField(verbose_name='HTML Content')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('detail', models.CharField(max_length=5000, verbose_name='Question')),
                ('active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_faq', models.BooleanField(default=True, verbose_name='Is Frequently Asked Question?')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Site Name')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('home_url', models.CharField(max_length=128, null=True, verbose_name='Home Url')),
                ('domain', models.CharField(help_text='To parse incoming requests and show correct page', max_length=128, null=True, verbose_name='domain')),
                ('application_start_date', models.DateField(default=datetime.datetime.now, verbose_name='Course Application Start Date')),
                ('application_end_date', models.DateField(default=datetime.datetime.now, verbose_name='Course Application End Date')),
                ('event_start_date', models.DateField(default=datetime.datetime.now, verbose_name='Event Start Date')),
                ('event_end_date', models.DateField(default=datetime.datetime.now, verbose_name='Event End Date')),
                ('docs_end_date', models.DateField(default=datetime.datetime.now, verbose_name='Docs End Date')),
                ('morning', models.FloatField(default=3.0, verbose_name='Total course hours at morning for one day')),
                ('afternoon', models.FloatField(default=3.5, verbose_name='Total course hours at afternoon for one day')),
                ('evening', models.FloatField(default=2.5, verbose_name='Total course hours at evening for one day')),
                ('needs_document', models.BooleanField(default=True, verbose_name='Site requires document')),
            ],
        ),
        migrations.CreateModel(
            name='TextBoxQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionno', models.IntegerField()),
                ('detail', models.CharField(max_length=700, verbose_name='Classic Questions')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_sitewide', models.BooleanField(default=False, verbose_name='Site Wide')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudur.Site')),
            ],
            options={
                'verbose_name': 'Classic Question',
                'verbose_name_plural': 'Classic Questions',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudur.Site'),
        ),
        migrations.AddField(
            model_name='content',
            name='menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mudur.Menu'),
        ),
        migrations.AddField(
            model_name='approvaldate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudur.Site'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mudur.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('order', 'site')]),
        ),
    ]
