# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-30 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudur', '0001_new_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='update_accommodation_end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Accommodation Update End Date'),
        ),
        migrations.AddField(
            model_name='textboxquestions',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is Visible?'),
        ),
    ]
