# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudur', '0011_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(upload_to='images/', verbose_name='Logo'),
        ),
    ]
