# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_new_initial'),
        ('mudur', '0001_new_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=4, verbose_name='Course No')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('approved', models.BooleanField(default=False)),
                ('application_is_open', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=350, verbose_name='URL')),
                ('authorized_trainer', models.ManyToManyField(related_name='authorized_trainer', to='userprofile.UserProfile', verbose_name='Authorized Trainers')),
                ('question', models.ManyToManyField(blank=True, to='mudur.Question', verbose_name='Question')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudur.Site')),
                ('textboxquestion', models.ManyToManyField(blank=True, to='mudur.TextBoxQuestions', verbose_name='Text Box Questions')),
                ('trainer', models.ManyToManyField(related_name='trainer', to='userprofile.UserProfile', verbose_name='Trainer')),
                ('trainess', models.ManyToManyField(blank=True, related_name='trainess', to='userprofile.UserProfile', verbose_name='Trainess')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='TrainessCourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_order', models.SmallIntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('trainess_approved', models.BooleanField(default=False)),
                ('instapprovedate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('consentemailsent', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Course')),
                ('trainess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
            options={
                'verbose_name': 'Trainess Course Record',
                'verbose_name_plural': 'Trainess Course Records',
                'ordering': ['trainess', 'preference_order'],
            },
        ),
        migrations.CreateModel(
            name='TrainessParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.CharField(choices=[('-1', 'Kurs Yapılmadı'), ('0', 'Katılmadı'), ('1', 'Yarısına Katıldı'), ('2', 'Katıldı')], default='0', max_length=3, verbose_name='Morning')),
                ('afternoon', models.CharField(choices=[('-1', 'Kurs Yapılmadı'), ('0', 'Katılmadı'), ('1', 'Yarısına Katıldı'), ('2', 'Katıldı')], default='0', max_length=3, verbose_name='Afternoon')),
                ('evening', models.CharField(choices=[('-1', 'Kurs Yapılmadı'), ('0', 'Katılmadı'), ('1', 'Yarısına Katıldı'), ('2', 'Katıldı')], default='0', max_length=3, verbose_name='Evening')),
                ('day', models.CharField(default='1', max_length=20, verbose_name='Day')),
                ('courserecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TrainessCourseRecord')),
            ],
            options={
                'verbose_name': 'Trainess Participation Information',
                'verbose_name_plural': 'Trainess Participation Information',
            },
        ),
        migrations.CreateModel(
            name='TrainessTestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='mudur.Answer')),
                ('tcourserecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TrainessCourseRecord')),
            ],
            options={
                'verbose_name': 'Trainess Test Answer',
                'verbose_name_plural': 'Trainess Test Answer',
            },
        ),
    ]
