# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_new_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_participant',
            field=models.IntegerField(default=20),
        ),
    ]
