# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20220811_2310'),
        ('training', '0002_course_max_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=200)),
                ('camp_year', models.IntegerField(default=0)),
                ('signature', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.UserProfile')),
            ],
        ),
    ]
