# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20160815_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainessparticipation',
            name='afternoon',
            field=models.CharField(choices=[('-1', 'Kurs Yapılmadı'), ('0', 'Katılmadı'), ('1', 'Yarısına Katıldı'), ('2', 'Katıldı')], default='0', max_length=3, verbose_name='Afternoon'),
        ),
        migrations.AlterField(
            model_name='trainessparticipation',
            name='day',
            field=models.CharField(default='1', max_length=20, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='trainessparticipation',
            name='evening',
            field=models.CharField(choices=[('-1', 'Kurs Yapılmadı'), ('0', 'Katılmadı'), ('1', 'Yarısına Katıldı'), ('2', 'Katıldı')], default='0', max_length=3, verbose_name='Evening'),
        ),
        migrations.AlterField(
            model_name='trainessparticipation',
            name='morning',
            field=models.CharField(choices=[('-1', 'Kurs Yapılmadı'), ('0', 'Katılmadı'), ('1', 'Yarısına Katıldı'), ('2', 'Katıldı')], default='0', max_length=3, verbose_name='Morning'),
        ),
    ]
