# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_userprofile_emergency_contact_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('version', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.AgreementCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.AgreementText')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilephoto',
            field=models.ImageField(help_text='Maximum 5 MB file is allowed.', upload_to=userprofile.models.user_directory_path, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofilebysite',
            name='document',
            field=models.FileField(blank=True, help_text='Maximum 10 MB file is allowed.', null=True, upload_to=userprofile.models.user_directory_path, verbose_name='Belge Ekle'),
        ),
        migrations.AlterUniqueTogether(
            name='agreementtext',
            unique_together=set([('version', 'category')]),
        ),
    ]
