# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mudur', '0001_new_initial'),
        ('userprofile', '0003_auto_20180615_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('body', models.TextField(verbose_name='İçerik')),
                ('attachment', models.FileField(blank=True, upload_to='feedback_files', verbose_name='Eklenti')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudur.Site', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_feedback_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile', verbose_name='Kullanıcı'),
        ),
    ]
