# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180615_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedbacks'},
        ),
        migrations.AlterField(
            model_name='agreementcategory',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='agreementtext',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
