# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20220730_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Processing', 'Sürüyor'), ('Closed', 'Cevaplandı')], default='New', max_length=12, verbose_name='Durum'),
        ),
    ]
