# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20220811_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobilephonenumber',
            field=models.CharField(blank=True, max_length=14, verbose_name='Mobile Phone Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empty_mobile_phone_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filled_mobile_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
