# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20220811_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yeni'), (2, 'Sürüyor'), (3, 'Cevaplandı')], default=1, verbose_name='Durum'),
        ),
    ]
