# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='extra',
            field=models.TextField(blank=True, default=''),
        ),
    ]
